### ISSUE TITLE
Facebook oauth login issue

### ISSUE THREAD

**Issue by ChuckIrvine** [cleverbeagle/pup#118]
I see this problem on a recurring basis on my production Galaxy instance. Note that I don't know whether this problem is pup related. I've submitted the same issue to Galaxy support.

1. I try to do an ouath login with my Facebook credentials.
2. I get a facebook error message saying that I don't have the right whitelist settings.
3. If I do a new deployment to my app to Galaxy, the problem goes away and I am able to login.

**Comment by cleverbeagle** [comment]
Hmm. This is likely due to Facebook's new OAuth login rules, but it's a bit odd that it's corrected by a redeployment. Though it costs a bit more, if you upgrade your Galaxy containers to enable IP whitelisting, they will share the public IP addresses used for Galaxy which you can add to your Facebook config in the developers site:

<img width="1394" alt="screen shot 2018-02-09 at 11 39 25 am" src="https://user-images.githubusercontent.com/23730234/36041415-0e6bde0e-0d8e-11e8-8b54-a3e784b40d4a.png">

You'd want to place the IPs in that "Server IP Whitelist" box. Can you confirm whether or not this helps to fix?

**Comment by ChuckIrvine** [comment]
My reading of that setting is that it is only applicable to those using Graph API. See https://developers.facebook.com/docs/facebook-login/security. Also, the fact that a deployment fixes the problem and that I have never specified values for that field makes me think that the problem lies elsewhere. 

Note: I just checked and I'm seeing the problem now. I'm going to do a deployment to see it that fixes the problem again.

**Comment by cleverbeagle** [comment]
Hey @ChuckIrvine, any word on this?

**Comment by ChuckIrvine** [comment]
No. The problem is still occuring. I have submitted a ticket to Galaxy and they are researching. I'm also going to submit a bug report to Facebook. It's probably safe to say that this isn't a pup issue.

**Comment by cleverbeagle** [comment]
@ChuckIrvine got it. Going to close this out for now but please leave a comment on this thread if you folks come to a solution :)
